### ISSUE TITLE
Unknown module 'DrawBattHolder'

### ISSUE THREAD

**Issue by mklengel** [M-oster/Advanced-Ultimate-Box-Maker#2]
Opening Advanced-Ultimate-Box-Maker-main.scad and setting SmallParts=yes (Customizer) leads to:

`WARNING: Ignoring unknown module 'DrawBattHolder' in file Advanced-Ultimate-Box-Maker-main.scad, line 1780`

**Comment by M-oster** [comment]
Oh, thanks for the hint. You can delete this part of  4 lines at the end of the main-script. That belongs to the expample with the mini-powersupply. DrawBattholder is referenced in Mycomponents.scad. But an empty case has no components inside and of cause no Batteryholder.
